insert into customers (customer_id, email, registration_date, location) values (1, 'mdetocqueville0@xing.com', '9/7/2024', 'Pakistan');
insert into customers (customer_id, email, registration_date, location) values (2, 'lkeele1@yahoo.co.jp', '5/19/2024', 'Colombia');
insert into customers (customer_id, email, registration_date, location) values (3, 'hgoodwell2@weather.com', '1/6/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (4, 'fbaccup3@hatena.ne.jp', '10/3/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (5, 'finett4@seattletimes.com', '9/11/2024', 'Mali');
insert into customers (customer_id, email, registration_date, location) values (6, 'wgarmans5@elpais.com', '8/20/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (7, 'eashment6@virginia.edu', '4/30/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (8, 'tgarces7@google.fr', '11/7/2024', 'Tanzania');
insert into customers (customer_id, email, registration_date, location) values (9, 'dsharman8@typepad.com', '9/24/2024', 'Equatorial Guinea');
insert into customers (customer_id, email, registration_date, location) values (10, 'hdeetlof9@washingtonpost.com', '3/5/2024', 'North Korea');
insert into customers (customer_id, email, registration_date, location) values (11, 'mmeerea@disqus.com', '7/23/2024', 'Japan');
insert into customers (customer_id, email, registration_date, location) values (12, 'wmacgebenayb@cnbc.com', '1/13/2025', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (13, 'hscarcec@fotki.com', '12/2/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (14, 'ibillinghamd@dedecms.com', '3/30/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (15, 'fdanielczyke@youtube.com', '7/7/2024', 'Latvia');
insert into customers (customer_id, email, registration_date, location) values (16, 'gdrohanef@gnu.org', '10/13/2024', 'Pakistan');
insert into customers (customer_id, email, registration_date, location) values (17, 'tgooddyg@ustream.tv', '12/12/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (18, 'jburwellh@princeton.edu', '12/16/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (19, 'bbartoszinskii@google.com.hk', '6/2/2024', 'Kazakhstan');
insert into customers (customer_id, email, registration_date, location) values (20, 'zwibrewj@accuweather.com', '7/20/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (21, 'jdallywaterk@bandcamp.com', '8/16/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (22, 'mguestel@columbia.edu', '2/10/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (23, 'tbwyem@latimes.com', '7/18/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (24, 'rteaguen@netscape.com', '9/16/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (25, 'ahallatto@pagesperso-orange.fr', '9/30/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (26, 'pplakp@goo.gl', '7/6/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (27, 'abartoszinskiq@ow.ly', '3/20/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (28, 'rsearchr@thetimes.co.uk', '4/25/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (29, 'sbarrouxs@unesco.org', '6/27/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (30, 'kwarrenert@163.com', '9/6/2024', 'Uganda');
insert into customers (customer_id, email, registration_date, location) values (31, 'dpeaurtu@samsung.com', '7/24/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (32, 'psweetzerv@163.com', '4/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (33, 'lgladmanw@imgur.com', '7/13/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (34, 'bglendenningx@blogspot.com', '10/14/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (35, 'ostansbiey@flavors.me', '8/30/2024', 'Mali');
insert into customers (customer_id, email, registration_date, location) values (36, 'agodbyz@senate.gov', '8/4/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (37, 'rpierro10@1und1.de', '5/9/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (38, 'ybembrick11@wikimedia.org', '9/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (39, 'tlaity12@dropbox.com', '4/25/2024', 'Argentina');
insert into customers (customer_id, email, registration_date, location) values (40, 'mcostin13@live.com', '4/4/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (41, 'jnicolls14@weebly.com', '3/19/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (42, 'hbenmore15@indiatimes.com', '5/1/2024', 'Greece');
insert into customers (customer_id, email, registration_date, location) values (43, 'rhunnicot16@cafepress.com', '2/18/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (44, 'jhan17@blogs.com', '8/6/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (45, 'ekennford18@virginia.edu', '11/25/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (46, 'gsherbrook19@desdev.cn', '11/5/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (47, 'jmacgorley1a@hugedomains.com', '5/18/2024', 'Ireland');
insert into customers (customer_id, email, registration_date, location) values (48, 'tpitney1b@phoca.cz', '6/9/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (49, 'awadge1c@who.int', '7/25/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (50, 'gsolman1d@tripadvisor.com', '5/22/2024', 'South Africa');
insert into customers (customer_id, email, registration_date, location) values (51, 'gbuntin1e@ebay.co.uk', '12/29/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (52, 'kescreet1f@prnewswire.com', '11/23/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (53, 'cchapier1g@cbc.ca', '8/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (54, 'hbagby1h@va.gov', '11/4/2024', 'Trinidad and Tobago');
insert into customers (customer_id, email, registration_date, location) values (55, 'nantley1i@independent.co.uk', '9/3/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (56, 'gskellen1j@reuters.com', '4/18/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (57, 'ihubeaux1k@fema.gov', '7/27/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (58, 'rbouller1l@discovery.com', '5/7/2024', 'Peru');
insert into customers (customer_id, email, registration_date, location) values (59, 'gebbers1m@nhs.uk', '5/23/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (60, 'fshervil1n@intel.com', '11/28/2024', 'Bulgaria');
insert into customers (customer_id, email, registration_date, location) values (61, 'cagney1o@slideshare.net', '3/25/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (62, 'lgilleon1p@wix.com', '7/31/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (63, 'epiddletown1q@marriott.com', '6/26/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (64, 'eharbin1r@paginegialle.it', '8/17/2024', 'Israel');
insert into customers (customer_id, email, registration_date, location) values (65, 'bgrimme1s@hp.com', '10/25/2024', 'Mexico');
insert into customers (customer_id, email, registration_date, location) values (66, 'cpiris1t@163.com', '3/19/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (67, 'ukryska1u@github.io', '1/1/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (68, 'esneath1v@simplemachines.org', '7/29/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (69, 'jdowyer1w@imageshack.us', '5/7/2024', 'Macedonia');
insert into customers (customer_id, email, registration_date, location) values (70, 'lruskin1x@addthis.com', '7/9/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (71, 'tlathwell1y@angelfire.com', '7/27/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (72, 'bmartland1z@ycombinator.com', '2/20/2024', 'Sierra Leone');
insert into customers (customer_id, email, registration_date, location) values (73, 'wkeeting20@ovh.net', '11/30/2024', 'Japan');
insert into customers (customer_id, email, registration_date, location) values (74, 'mdimond21@jiathis.com', '2/4/2024', 'Montenegro');
insert into customers (customer_id, email, registration_date, location) values (75, 'cstoll22@123-reg.co.uk', '9/24/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (76, 'cgodridge23@edublogs.org', '10/15/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (77, 'tashwin24@wufoo.com', '11/20/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (78, 'cbroad25@fda.gov', '7/26/2024', 'Comoros');
insert into customers (customer_id, email, registration_date, location) values (79, 'ofrayn26@weebly.com', '9/29/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (80, 'nbourdice27@ucla.edu', '1/12/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (81, 'mhenzer28@sakura.ne.jp', '9/10/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (82, 'mjakubovits29@independent.co.uk', '6/15/2024', 'Venezuela');
insert into customers (customer_id, email, registration_date, location) values (83, 'kwalbridge2a@google.com.br', '11/22/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (84, 'ckauffman2b@princeton.edu', '10/24/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (85, 'hdurden2c@ezinearticles.com', '6/16/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (86, 'ejentzsch2d@geocities.com', '9/28/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (87, 'marlott2e@youtu.be', '4/22/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (88, 'prickell2f@goo.ne.jp', '4/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (89, 'tible2g@nsw.gov.au', '1/31/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (90, 'vverillo2h@usgs.gov', '3/10/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (91, 'cdennerley2i@prweb.com', '5/19/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (92, 'bpayne2j@github.com', '5/22/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (93, 'rjarman2k@example.com', '12/12/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (94, 'wwyllie2l@ebay.com', '11/4/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (95, 'nslight2m@wikimedia.org', '1/6/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (96, 'lmcindoe2n@unblog.fr', '5/2/2024', 'Bulgaria');
insert into customers (customer_id, email, registration_date, location) values (97, 'rboutellier2o@naver.com', '8/16/2024', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (98, 'esharpous2p@topsy.com', '7/1/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (99, 'agreenhill2q@dailymail.co.uk', '3/15/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (100, 'nchilton2r@example.com', '3/7/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (101, 'tmoralas2s@utexas.edu', '11/23/2024', 'Tajikistan');
insert into customers (customer_id, email, registration_date, location) values (102, 'mmcgaw2t@cdbaby.com', '11/13/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (103, 'mfortye2u@freewebs.com', '10/7/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (104, 'jbrompton2v@t-online.de', '5/26/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (105, 'bbeedom2w@wordpress.org', '12/14/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (106, 'dfreen2x@feedburner.com', '10/23/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (107, 'cwreford2y@nbcnews.com', '8/27/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (108, 'thawkshaw2z@ca.gov', '7/5/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (109, 'cmeeks30@cnet.com', '11/12/2024', 'Spain');
insert into customers (customer_id, email, registration_date, location) values (110, 'bpietesch31@answers.com', '7/3/2024', 'Greece');
insert into customers (customer_id, email, registration_date, location) values (111, 'hboldison32@histats.com', '4/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (112, 'edifrisco33@live.com', '8/16/2024', 'Peru');
insert into customers (customer_id, email, registration_date, location) values (113, 'acogdell34@oracle.com', '7/8/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (114, 'sdevillier35@unblog.fr', '5/15/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (115, 'scoryndon36@1688.com', '5/4/2024', 'Bulgaria');
insert into customers (customer_id, email, registration_date, location) values (116, 'cbiner37@technorati.com', '11/5/2024', 'Nigeria');
insert into customers (customer_id, email, registration_date, location) values (117, 'jsprowles38@fema.gov', '3/10/2024', 'Switzerland');
insert into customers (customer_id, email, registration_date, location) values (118, 'loscanlon39@cbc.ca', '5/28/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (119, 'smanchett3a@chron.com', '2/7/2024', 'Honduras');
insert into customers (customer_id, email, registration_date, location) values (120, 'hcardow3b@fc2.com', '12/12/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (121, 'abrittain3c@usnews.com', '1/6/2025', 'United States');
insert into customers (customer_id, email, registration_date, location) values (122, 'ikinnie3d@joomla.org', '8/10/2024', 'New Caledonia');
insert into customers (customer_id, email, registration_date, location) values (123, 'mtatersale3e@seesaa.net', '8/9/2024', 'Afghanistan');
insert into customers (customer_id, email, registration_date, location) values (124, 'cmacallaster3f@nbcnews.com', '5/20/2024', 'Ukraine');
insert into customers (customer_id, email, registration_date, location) values (125, 'udownham3g@amazon.com', '6/19/2024', 'Georgia');
insert into customers (customer_id, email, registration_date, location) values (126, 'tadamovsky3h@jalbum.net', '12/29/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (127, 'krowden3i@canalblog.com', '3/9/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (128, 'deskriet3j@patch.com', '2/23/2024', 'Mongolia');
insert into customers (customer_id, email, registration_date, location) values (129, 'vmatyushonok3k@answers.com', '11/10/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (130, 'bbroadbear3l@chicagotribune.com', '2/20/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (131, 'epeschet3m@squarespace.com', '1/4/2025', 'Dominican Republic');
insert into customers (customer_id, email, registration_date, location) values (132, 'ctichner3n@liveinternet.ru', '7/17/2024', 'Japan');
insert into customers (customer_id, email, registration_date, location) values (133, 'lavraam3o@chron.com', '10/2/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (134, 'gschoenrock3p@aboutads.info', '3/21/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (135, 'mbour3q@dailymail.co.uk', '10/9/2024', 'United Kingdom');
insert into customers (customer_id, email, registration_date, location) values (136, 'tbrymham3r@vimeo.com', '10/2/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (137, 'cwasylkiewicz3s@github.io', '12/22/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (138, 'pguess3t@baidu.com', '2/8/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (139, 'gglasheen3u@nasa.gov', '5/30/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (140, 'tocanavan3v@csmonitor.com', '1/5/2025', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (141, 'rhallbord3w@google.ru', '8/11/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (142, 'gcolliard3x@bloglovin.com', '2/2/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (143, 'ahynard3y@yandex.ru', '5/15/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (144, 'amacalpin3z@un.org', '5/11/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (145, 'rbenezet40@163.com', '5/7/2024', 'Bosnia and Herzegovina');
insert into customers (customer_id, email, registration_date, location) values (146, 'mschober41@symantec.com', '1/24/2024', 'Myanmar');
insert into customers (customer_id, email, registration_date, location) values (147, 'cstockport42@berkeley.edu', '3/2/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (148, 'louver43@amazon.co.uk', '1/14/2025', 'Norway');
insert into customers (customer_id, email, registration_date, location) values (149, 'cbarbery44@spotify.com', '7/29/2024', 'Ukraine');
insert into customers (customer_id, email, registration_date, location) values (150, 'bleddie45@1und1.de', '12/3/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (151, 'scranstoun46@sina.com.cn', '5/15/2024', 'Greece');
insert into customers (customer_id, email, registration_date, location) values (152, 'rrosson47@zimbio.com', '9/16/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (153, 'tcowburn48@mozilla.com', '11/27/2024', 'Morocco');
insert into customers (customer_id, email, registration_date, location) values (154, 'ogeator49@is.gd', '2/13/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (155, 'wmccowen4a@lycos.com', '12/9/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (156, 'faland4b@freewebs.com', '8/15/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (157, 'mtomala4c@webs.com', '1/3/2025', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (158, 'ejamme4d@google.ca', '3/30/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (159, 'htrevon4e@salon.com', '7/24/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (160, 'fpiercey4f@zimbio.com', '12/27/2024', 'Bosnia and Herzegovina');
insert into customers (customer_id, email, registration_date, location) values (161, 'lgreeding4g@csmonitor.com', '11/13/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (162, 'itinsey4h@amazon.com', '4/21/2024', 'Taiwan');
insert into customers (customer_id, email, registration_date, location) values (163, 'dolyet4i@fotki.com', '6/5/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (164, 'bglaserman4j@state.tx.us', '10/18/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (165, 'amcgrane4k@huffingtonpost.com', '10/21/2024', 'Mauritius');
insert into customers (customer_id, email, registration_date, location) values (166, 'kscarborough4l@wufoo.com', '2/7/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (167, 'kwherry4m@ftc.gov', '4/15/2024', 'Serbia');
insert into customers (customer_id, email, registration_date, location) values (168, 'spostgate4n@purevolume.com', '7/7/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (169, 'gnoweak4o@a8.net', '10/2/2024', 'Thailand');
insert into customers (customer_id, email, registration_date, location) values (170, 'ecroce4p@dagondesign.com', '6/20/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (171, 'fmacguigan4q@comcast.net', '1/1/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (172, 'bameerbeg4r@hubpages.com', '12/12/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (173, 'mfarrin4s@netlog.com', '7/4/2024', 'Madagascar');
insert into customers (customer_id, email, registration_date, location) values (174, 'kmacfadin4t@yahoo.co.jp', '1/8/2025', 'Kenya');
insert into customers (customer_id, email, registration_date, location) values (175, 'mschach4u@businesswire.com', '11/14/2024', 'Slovenia');
insert into customers (customer_id, email, registration_date, location) values (176, 'jjohnikin4v@etsy.com', '3/24/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (177, 'moganian4w@wikispaces.com', '5/12/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (178, 'mdomenicone4x@jalbum.net', '8/12/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (179, 'tpentlow4y@linkedin.com', '12/18/2024', 'Iraq');
insert into customers (customer_id, email, registration_date, location) values (180, 'osheldon4z@netvibes.com', '5/1/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (181, 'aleconte50@histats.com', '2/17/2024', 'Colombia');
insert into customers (customer_id, email, registration_date, location) values (182, 'mhatton51@answers.com', '2/28/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (183, 'elelande52@booking.com', '9/28/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (184, 'wrubin53@msn.com', '4/15/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (185, 'channer54@alibaba.com', '3/31/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (186, 'ldewitt55@craigslist.org', '6/6/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (187, 'gnightingale56@163.com', '3/22/2024', 'Vietnam');
insert into customers (customer_id, email, registration_date, location) values (188, 'cmeo57@shutterfly.com', '8/28/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (189, 'ddoghartie58@pbs.org', '5/3/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (190, 'kwade59@ft.com', '4/15/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (191, 'dbeeckx5a@ibm.com', '1/30/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (192, 'thaine5b@mysql.com', '7/23/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (193, 'jeverex5c@feedburner.com', '7/15/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (194, 'thaslin5d@army.mil', '1/25/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (195, 'hlinguard5e@360.cn', '1/9/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (196, 'mowlner5f@bbb.org', '9/3/2024', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (197, 'agovey5g@homestead.com', '3/22/2024', 'Malaysia');
insert into customers (customer_id, email, registration_date, location) values (198, 'lmelby5h@irs.gov', '7/9/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (199, 'mphalp5i@mtv.com', '8/26/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (200, 'tpepper5j@goo.ne.jp', '8/31/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (201, 'bsalmon5k@t.co', '12/9/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (202, 'tbougen5l@deviantart.com', '11/4/2024', 'Ukraine');
insert into customers (customer_id, email, registration_date, location) values (203, 'kwadie5m@slideshare.net', '10/11/2024', 'Slovenia');
insert into customers (customer_id, email, registration_date, location) values (204, 'cspellessy5n@businessinsider.com', '2/19/2024', 'Morocco');
insert into customers (customer_id, email, registration_date, location) values (205, 'rgoudge5o@huffingtonpost.com', '8/17/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (206, 'pgorden5p@economist.com', '3/21/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (207, 'gaberkirdo5q@java.com', '4/1/2024', 'Nicaragua');
insert into customers (customer_id, email, registration_date, location) values (208, 'vmacphail5r@oakley.com', '10/23/2024', 'Palestinian Territory');
insert into customers (customer_id, email, registration_date, location) values (209, 'mlarwood5s@archive.org', '5/28/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (210, 'dglascott5t@usatoday.com', '9/10/2024', 'Malaysia');
insert into customers (customer_id, email, registration_date, location) values (211, 'gbrauner5u@oakley.com', '6/21/2024', 'Belize');
insert into customers (customer_id, email, registration_date, location) values (212, 'pgindghill5v@php.net', '6/9/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (213, 'jlivingston5w@mapy.cz', '5/10/2024', 'Tajikistan');
insert into customers (customer_id, email, registration_date, location) values (214, 'cchmiel5x@nydailynews.com', '4/7/2024', 'Dominica');
insert into customers (customer_id, email, registration_date, location) values (215, 'gpreshous5y@wix.com', '3/14/2024', 'Macedonia');
insert into customers (customer_id, email, registration_date, location) values (216, 'begginton5z@zimbio.com', '12/12/2024', 'Costa Rica');
insert into customers (customer_id, email, registration_date, location) values (217, 'hdadds60@reverbnation.com', '10/27/2024', 'Malta');
insert into customers (customer_id, email, registration_date, location) values (218, 'vduffrie61@addtoany.com', '1/6/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (219, 'echessil62@topsy.com', '12/23/2024', 'Canada');
insert into customers (customer_id, email, registration_date, location) values (220, 'oduligal63@gov.uk', '5/28/2024', 'Iraq');
insert into customers (customer_id, email, registration_date, location) values (221, 'rolivi64@shinystat.com', '4/6/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (222, 'sspensley65@umich.edu', '10/5/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (223, 'cbirtwell66@ft.com', '4/29/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (224, 'clavelle67@intel.com', '10/30/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (225, 'lridsdale68@netvibes.com', '9/9/2024', 'Solomon Islands');
insert into customers (customer_id, email, registration_date, location) values (226, 'teddins69@macromedia.com', '3/2/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (227, 'glockton6a@ft.com', '10/10/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (228, 'mvatcher6b@pinterest.com', '7/25/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (229, 'cjull6c@newsvine.com', '9/7/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (230, 'pthomasset6d@amazon.co.uk', '3/19/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (231, 'kbeachem6e@ftc.gov', '12/1/2024', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (232, 'tzavattari6f@google.com.au', '11/17/2024', 'Sweden');
insert into customers (customer_id, email, registration_date, location) values (233, 'lmaylour6g@odnoklassniki.ru', '4/27/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (234, 'zfuller6h@addthis.com', '7/31/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (235, 'fscouler6i@omniture.com', '7/1/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (236, 'bkave6j@1688.com', '6/24/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (237, 'babrahart6k@symantec.com', '4/7/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (238, 'ljobling6l@usnews.com', '1/15/2025', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (239, 'fhambly6m@mit.edu', '9/7/2024', 'Argentina');
insert into customers (customer_id, email, registration_date, location) values (240, 'rbaszniak6n@twitpic.com', '1/20/2025', 'China');
insert into customers (customer_id, email, registration_date, location) values (241, 'ssoper6o@sun.com', '12/21/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (242, 'ccogan6p@homestead.com', '4/28/2024', 'Japan');
insert into customers (customer_id, email, registration_date, location) values (243, 'caloway6q@nyu.edu', '5/15/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (244, 'lstrickland6r@state.tx.us', '1/25/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (245, 'sdarrell6s@moonfruit.com', '4/15/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (246, 'cbrooke6t@godaddy.com', '6/8/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (247, 'talban6u@tuttocitta.it', '12/11/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (248, 'hmacgiffin6v@amazon.co.uk', '2/20/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (249, 'espenceley6w@github.com', '9/15/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (250, 'emartlew6x@networkadvertising.org', '2/18/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (251, 'bparrott6y@indiegogo.com', '8/8/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (252, 'cthunderman6z@amazon.com', '10/28/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (253, 'kplayden70@dagondesign.com', '9/8/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (254, 'amunt71@yahoo.co.jp', '4/14/2024', 'Myanmar');
insert into customers (customer_id, email, registration_date, location) values (255, 'pbirkhead72@hc360.com', '12/22/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (256, 'gwhyberd73@nydailynews.com', '10/7/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (257, 'gpeggs74@npr.org', '11/19/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (258, 'iheaslip75@last.fm', '8/31/2024', 'Colombia');
insert into customers (customer_id, email, registration_date, location) values (259, 'fvandenvelden76@apache.org', '7/19/2024', 'France');
insert into customers (customer_id, email, registration_date, location) values (260, 'qeckford77@sourceforge.net', '7/24/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (261, 'wmacnally78@mysql.com', '7/8/2024', 'Japan');
insert into customers (customer_id, email, registration_date, location) values (262, 'bilsley79@scientificamerican.com', '2/29/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (263, 'treven7a@blogtalkradio.com', '11/20/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (264, 'awestgarth7b@typepad.com', '12/1/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (265, 'lgreenough7c@blogger.com', '5/4/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (266, 'dworpole7d@patch.com', '4/21/2024', 'Czech Republic');
insert into customers (customer_id, email, registration_date, location) values (267, 'mriep7e@auda.org.au', '2/8/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (268, 'pcicchelli7f@economist.com', '4/12/2024', 'Paraguay');
insert into customers (customer_id, email, registration_date, location) values (269, 'msansam7g@tripadvisor.com', '10/21/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (270, 'aoldroyd7h@pen.io', '2/3/2024', 'Guatemala');
insert into customers (customer_id, email, registration_date, location) values (271, 'rcloney7i@amazon.de', '3/27/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (272, 'aplace7j@angelfire.com', '5/26/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (273, 'vhryncewicz7k@columbia.edu', '4/17/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (274, 'gjansik7l@sitemeter.com', '12/27/2024', 'Australia');
insert into customers (customer_id, email, registration_date, location) values (275, 'cfarries7m@angelfire.com', '3/2/2024', 'Pakistan');
insert into customers (customer_id, email, registration_date, location) values (276, 'mrayson7n@ocn.ne.jp', '10/2/2024', 'Vietnam');
insert into customers (customer_id, email, registration_date, location) values (277, 'bnoar7o@japanpost.jp', '5/21/2024', 'Russia');
insert into customers (customer_id, email, registration_date, location) values (278, 'gcorneliussen7p@sitemeter.com', '6/10/2024', 'Uruguay');
insert into customers (customer_id, email, registration_date, location) values (279, 'tpaoletti7q@merriam-webster.com', '5/13/2024', 'Poland');
insert into customers (customer_id, email, registration_date, location) values (280, 'ttulleth7r@imgur.com', '3/2/2024', 'Belarus');
insert into customers (customer_id, email, registration_date, location) values (281, 'lbrowett7s@fotki.com', '10/20/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (282, 'akirkness7t@fc2.com', '11/18/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (283, 'mgirth7u@ted.com', '4/24/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (284, 'abamsey7v@nbcnews.com', '4/19/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (285, 'screbo7w@ucoz.ru', '5/13/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (286, 'mgoldsack7x@chronoengine.com', '7/24/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (287, 'cjoret7y@cnbc.com', '9/7/2024', 'Ecuador');
insert into customers (customer_id, email, registration_date, location) values (288, 'lwhittenbury7z@businesswire.com', '2/10/2024', 'Germany');
insert into customers (customer_id, email, registration_date, location) values (289, 'sellaman80@ucoz.com', '3/30/2024', 'Indonesia');
insert into customers (customer_id, email, registration_date, location) values (290, 'sspalls81@weebly.com', '5/22/2024', 'Brazil');
insert into customers (customer_id, email, registration_date, location) values (291, 'rivanuschka82@smugmug.com', '10/22/2024', 'China');
insert into customers (customer_id, email, registration_date, location) values (292, 'rbulward83@google.pl', '4/16/2024', 'United States');
insert into customers (customer_id, email, registration_date, location) values (293, 'hsillitoe84@example.com', '10/14/2024', 'Peru');
insert into customers (customer_id, email, registration_date, location) values (294, 'ppolle85@walmart.com', '7/25/2024', 'Portugal');
insert into customers (customer_id, email, registration_date, location) values (295, 'agiannoni86@salon.com', '9/19/2024', 'Venezuela');
insert into customers (customer_id, email, registration_date, location) values (296, 'mmeader87@sbwire.com', '5/18/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (297, 'apaulucci88@oaic.gov.au', '8/24/2024', 'Montenegro');
insert into customers (customer_id, email, registration_date, location) values (298, 'lhaynesford89@goo.gl', '1/16/2025', 'Albania');
insert into customers (customer_id, email, registration_date, location) values (299, 'lgligoraci8a@gizmodo.com', '10/16/2024', 'Philippines');
insert into customers (customer_id, email, registration_date, location) values (300, 'kallonby8b@freewebs.com', '6/28/2024', 'Czech Republic');
