insert into products (product_id, product_name, category, price, stock_level) values (1, 'Asus ProArt P16 (H7606)', 'Business Laptops', 53.32, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (2, 'Macbook Pro M4', 'Intel/AMD Laptops', 56.2, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (3, 'Macbook Pro M2', 'Professional Laptops', 1.42, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (4, 'Microsoft Surface Laptop 7', 'Business Laptops', 97.0, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (5, 'Macbook Pro M1', 'ARM Laptops', 24.29, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (6, 'Macbook Pro M4', 'Intel/AMD Laptops', 65.83, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (7, 'Macbook Pro M1', 'ARM Laptops', 96.56, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (8, 'ASUS Zenbook 14 OLED Touch', 'Professional Laptops', 73.33, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (9, 'Macbook Pro M4', 'ARM Laptops', 70.83, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (10, 'Microsoft Surface Laptop 7', 'Professional Laptops', 1.49, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (11, 'Macbook Pro M1', 'ARM Laptops', 84.33, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (12, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 70.45, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (13, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 48.5, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (14, 'Macbook Air M3', 'Professional Laptops', 91.34, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (15, 'Macbook Air M3', 'Professional Laptops', 2.16, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (16, 'Macbook Pro M2', 'Performance Laptops', 9.48, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (17, 'Macbook Pro M1', 'Performance Laptops', 8.62, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (18, 'Macbook Pro M4', 'Business Laptops', 16.35, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (19, 'Macbook Pro M1', 'Business Laptops', 2.07, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (20, 'Dell Precision 5690', 'ARM Laptops', 92.26, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (21, 'Macbook Pro M2', 'Intel/AMD Laptops', 48.27, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (22, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 60.28, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (23, 'Microsoft Surface Laptop 7', 'ARM Laptops', 48.92, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (24, 'Macbook Pro Intel i9', 'ARM Laptops', 18.89, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (25, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 92.24, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (26, 'Asus ProArt P16 (H7606)', 'Business Laptops', 94.16, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (27, 'Macbook Pro M4', 'Intel/AMD Laptops', 40.83, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (28, 'Macbook Pro Intel i9', 'Professional Laptops', 11.5, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (29, 'Dell Precision 5690', 'Intel/AMD Laptops', 96.7, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (30, 'Macbook Pro Intel i9', 'Intel/AMD Laptops', 57.51, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (31, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 20.28, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (32, 'Macbook Pro M2', 'ARM Laptops', 98.06, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (33, 'Microsoft Surface Laptop 7', 'Professional Laptops', 83.58, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (34, 'Macbook Air M3', 'Business Laptops', 77.5, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (35, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Intel/AMD Laptops', 33.05, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (36, 'Dell Precision 5690', 'ARM Laptops', 43.9, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (37, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 18.47, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (38, 'Asus ProArt P16 (H7606)', 'Business Laptops', 71.66, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (39, 'Macbook Pro Intel i9', 'Professional Laptops', 64.27, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (40, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 48.18, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (41, 'Macbook Pro M4', 'Business Laptops', 13.89, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (42, 'Microsoft Surface Laptop 7', 'ARM Laptops', 6.6, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (43, 'Macbook Pro M4', 'Intel/AMD Laptops', 40.86, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (44, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 30.11, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (45, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 81.86, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (46, 'Macbook Pro M1', 'Intel/AMD Laptops', 89.75, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (47, 'Macbook Pro M2', 'Intel/AMD Laptops', 25.78, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (48, 'Microsoft Surface Laptop 7', 'Professional Laptops', 54.49, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (49, 'Dell Precision 5690', 'ARM Laptops', 82.73, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (50, 'Microsoft Surface Laptop 7', 'ARM Laptops', 82.89, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (51, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 17.59, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (52, 'Macbook Pro M2', 'ARM Laptops', 63.17, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (53, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 86.25, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (54, 'Macbook Pro Intel i9', 'Professional Laptops', 71.03, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (55, 'Macbook Pro Intel i9', 'Intel/AMD Laptops', 6.12, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (56, 'Macbook Pro M2', 'Performance Laptops', 83.84, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (57, 'Macbook Pro M4', 'Business Laptops', 89.4, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (58, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 58.34, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (59, 'Microsoft Surface Laptop 7', 'Performance Laptops', 77.93, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (60, 'Macbook Air M3', 'ARM Laptops', 72.52, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (61, 'Macbook Pro M2', 'Professional Laptops', 1.22, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (62, 'Macbook Pro M1', 'Business Laptops', 66.81, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (63, 'Macbook Pro Intel i9', 'Intel/AMD Laptops', 69.27, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (64, 'Dell Precision 5690', 'Intel/AMD Laptops', 21.26, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (65, 'Macbook Air M3', 'Performance Laptops', 53.53, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (66, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 23.06, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (67, 'Microsoft Surface Laptop 7', 'ARM Laptops', 52.99, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (68, 'Microsoft Surface Laptop 7', 'Business Laptops', 30.23, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (69, 'Macbook Pro M4', 'Performance Laptops', 88.88, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (70, 'Macbook Pro Intel i9', 'Professional Laptops', 19.01, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (71, 'Asus ProArt P16 (H7606)', 'Intel/AMD Laptops', 7.08, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (72, 'Macbook Pro M4', 'ARM Laptops', 77.99, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (73, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 66.07, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (74, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Professional Laptops', 59.29, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (75, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 71.87, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (76, 'Macbook Pro M4', 'Business Laptops', 2.57, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (77, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 60.24, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (78, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 88.62, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (79, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 84.28, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (80, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 73.13, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (81, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 66.5, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (82, 'Macbook Air M3', 'Intel/AMD Laptops', 97.31, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (83, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 78.38, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (84, 'Macbook Pro M4', 'Professional Laptops', 10.54, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (85, 'Dell Precision 5690', 'Business Laptops', 91.35, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (86, 'Macbook Pro M1', 'Professional Laptops', 1.88, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (87, 'Dell Precision 5690', 'Performance Laptops', 93.12, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (88, 'Macbook Pro M4', 'ARM Laptops', 64.46, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (89, 'ASUS Zenbook 14 OLED Touch', 'Professional Laptops', 74.65, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (90, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 18.93, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (91, 'Dell Precision 5690', 'ARM Laptops', 11.59, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (92, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Professional Laptops', 96.98, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (93, 'Macbook Air M3', 'ARM Laptops', 23.93, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (94, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 79.42, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (95, 'Macbook Pro M1', 'Business Laptops', 85.33, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (96, 'Lenovo ThinkPad X1 Carbon Gen 12', 'ARM Laptops', 11.25, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (97, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 28.05, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (98, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 14.37, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (99, 'Macbook Pro M1', 'Business Laptops', 76.69, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (100, 'Macbook Pro Intel i9', 'Business Laptops', 16.55, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (101, 'Macbook Pro M1', 'ARM Laptops', 36.64, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (102, 'Macbook Pro M4', 'ARM Laptops', 35.47, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (103, 'Macbook Pro M2', 'Professional Laptops', 7.47, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (104, 'Microsoft Surface Laptop 7', 'Professional Laptops', 81.52, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (105, 'Macbook Pro M4', 'ARM Laptops', 44.93, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (106, 'Macbook Air M3', 'Business Laptops', 80.79, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (107, 'Microsoft Surface Laptop 7', 'Business Laptops', 75.78, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (108, 'Macbook Air M3', 'Performance Laptops', 77.03, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (109, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 18.73, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (110, 'ASUS Zenbook 14 OLED Touch', 'Professional Laptops', 76.66, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (111, 'Microsoft Surface Laptop 7', 'ARM Laptops', 85.73, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (112, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 63.86, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (113, 'Macbook Pro M4', 'Intel/AMD Laptops', 43.76, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (114, 'ASUS Zenbook 14 OLED Touch', 'ARM Laptops', 70.75, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (115, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 3.03, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (116, 'Dell Precision 5690', 'ARM Laptops', 38.4, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (117, 'Macbook Pro M1', 'Intel/AMD Laptops', 26.2, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (118, 'Dell Precision 5690', 'Professional Laptops', 12.37, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (119, 'Macbook Air M3', 'ARM Laptops', 11.57, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (120, 'Macbook Pro M1', 'Performance Laptops', 57.73, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (121, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 73.54, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (122, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 66.32, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (123, 'Dell Precision 5690', 'Professional Laptops', 41.79, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (124, 'Macbook Air M3', 'Performance Laptops', 21.21, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (125, 'Dell Precision 5690', 'Business Laptops', 86.03, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (126, 'Macbook Pro Intel i9', 'Business Laptops', 13.31, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (127, 'Macbook Pro M4', 'Performance Laptops', 39.12, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (128, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 96.51, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (129, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 13.24, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (130, 'Macbook Air M3', 'Performance Laptops', 17.18, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (131, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 86.33, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (132, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 25.42, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (133, 'Macbook Pro M2', 'Business Laptops', 69.86, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (134, 'Macbook Air M3', 'Intel/AMD Laptops', 61.73, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (135, 'Macbook Pro Intel i9', 'Business Laptops', 25.96, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (136, 'Macbook Air M3', 'Intel/AMD Laptops', 50.74, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (137, 'Microsoft Surface Laptop 7', 'ARM Laptops', 73.5, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (138, 'Macbook Air M3', 'ARM Laptops', 34.35, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (139, 'Macbook Air M3', 'Business Laptops', 28.76, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (140, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 98.66, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (141, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 85.96, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (142, 'Microsoft Surface Laptop 7', 'Performance Laptops', 91.96, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (143, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 43.73, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (144, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 93.19, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (145, 'Macbook Pro M1', 'Professional Laptops', 87.66, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (146, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 47.37, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (147, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 75.83, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (148, 'Macbook Pro Intel i9', 'Business Laptops', 30.22, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (149, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 78.11, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (150, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 91.57, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (151, 'Macbook Air M3', 'Intel/AMD Laptops', 19.37, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (152, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 71.14, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (153, 'Macbook Pro M1', 'Business Laptops', 36.19, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (154, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 91.78, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (155, 'Macbook Pro Intel i9', 'Business Laptops', 12.61, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (156, 'Macbook Pro Intel i9', 'Business Laptops', 67.36, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (157, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 56.19, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (158, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 58.74, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (159, 'Macbook Pro M4', 'ARM Laptops', 64.94, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (160, 'Dell Precision 5690', 'Business Laptops', 35.12, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (161, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Professional Laptops', 30.77, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (162, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 95.92, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (163, 'ASUS Zenbook 14 OLED Touch', 'Professional Laptops', 51.97, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (164, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 87.66, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (165, 'Asus ProArt P16 (H7606)', 'Intel/AMD Laptops', 16.22, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (166, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 11.37, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (167, 'Macbook Air M3', 'ARM Laptops', 66.65, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (168, 'ASUS Zenbook 14 OLED Touch', 'ARM Laptops', 32.49, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (169, 'Macbook Pro Intel i9', 'ARM Laptops', 70.79, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (170, 'Dell Precision 5690', 'Professional Laptops', 60.32, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (171, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 97.23, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (172, 'Macbook Pro M1', 'ARM Laptops', 77.53, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (173, 'Macbook Pro M2', 'Professional Laptops', 48.66, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (174, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 36.34, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (175, 'Lenovo ThinkPad X1 Carbon Gen 12', 'ARM Laptops', 87.81, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (176, 'Macbook Pro M4', 'ARM Laptops', 81.69, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (177, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Professional Laptops', 9.71, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (178, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 69.59, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (179, 'Dell Precision 5690', 'Professional Laptops', 23.6, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (180, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 37.85, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (181, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 37.54, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (182, 'Macbook Pro M1', 'Business Laptops', 8.67, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (183, 'Macbook Pro M1', 'Professional Laptops', 8.87, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (184, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 1.8, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (185, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 68.11, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (186, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 71.24, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (187, 'Dell Precision 5690', 'Business Laptops', 53.59, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (188, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 97.84, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (189, 'Asus ProArt P16 (H7606)', 'Performance Laptops', 84.63, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (190, 'Macbook Pro Intel i9', 'Business Laptops', 70.29, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (191, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 63.34, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (192, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 85.92, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (193, 'Macbook Pro M2', 'ARM Laptops', 73.61, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (194, 'Macbook Pro M2', 'ARM Laptops', 36.8, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (195, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 76.14, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (196, 'Macbook Pro M4', 'Intel/AMD Laptops', 14.1, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (197, 'Macbook Pro Intel i9', 'Performance Laptops', 79.68, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (198, 'Dell Precision 5690', 'Performance Laptops', 90.51, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (199, 'Macbook Pro Intel i9', 'Performance Laptops', 36.76, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (200, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 69.36, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (201, 'Macbook Pro M4', 'ARM Laptops', 96.61, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (202, 'Dell Precision 5690', 'Business Laptops', 84.19, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (203, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Intel/AMD Laptops', 88.21, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (204, 'Macbook Pro M2', 'Professional Laptops', 60.39, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (205, 'Microsoft Surface Laptop 7', 'Professional Laptops', 72.32, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (206, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 88.67, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (207, 'Dell Precision 5690', 'ARM Laptops', 89.36, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (208, 'Macbook Pro Intel i9', 'Business Laptops', 80.75, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (209, 'Microsoft Surface Laptop 7', 'Professional Laptops', 88.49, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (210, 'Macbook Air M3', 'ARM Laptops', 74.11, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (211, 'Macbook Pro M4', 'ARM Laptops', 96.39, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (212, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 38.12, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (213, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 96.84, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (214, 'Dell Precision 5690', 'Professional Laptops', 96.29, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (215, 'Macbook Pro M2', 'Professional Laptops', 34.4, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (216, 'Macbook Pro M4', 'Professional Laptops', 78.76, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (217, 'Macbook Pro M2', 'ARM Laptops', 11.06, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (218, 'Dell Precision 5690', 'Business Laptops', 15.72, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (219, 'ASUS Zenbook 14 OLED Touch', 'ARM Laptops', 47.49, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (220, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 19.11, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (221, 'Macbook Pro M2', 'Professional Laptops', 53.42, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (222, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 32.91, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (223, 'Macbook Air M3', 'ARM Laptops', 7.32, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (224, 'Macbook Pro M1', 'Business Laptops', 49.28, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (225, 'Dell Precision 5690', 'Intel/AMD Laptops', 56.33, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (226, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 8.33, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (227, 'Macbook Air M3', 'Intel/AMD Laptops', 64.51, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (228, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 31.92, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (229, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 12.63, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (230, 'Macbook Pro M4', 'Professional Laptops', 42.67, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (231, 'Macbook Pro Intel i9', 'ARM Laptops', 47.26, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (232, 'Macbook Pro M2', 'Business Laptops', 29.18, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (233, 'Asus ProArt P16 (H7606)', 'Business Laptops', 45.93, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (234, 'Macbook Pro M2', 'Professional Laptops', 82.96, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (235, 'Macbook Pro M4', 'Business Laptops', 79.52, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (236, 'Macbook Pro M4', 'Professional Laptops', 78.43, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (237, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 82.09, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (238, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 43.1, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (239, 'Macbook Pro Intel i9', 'Intel/AMD Laptops', 92.23, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (240, 'Asus ProArt P16 (H7606)', 'Professional Laptops', 62.33, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (241, 'Macbook Pro M2', 'ARM Laptops', 35.32, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (242, 'ASUS Zenbook 14 OLED Touch', 'Business Laptops', 62.07, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (243, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 32.33, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (244, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 36.08, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (245, 'Macbook Pro M2', 'Professional Laptops', 6.96, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (246, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 98.04, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (247, 'ASUS Zenbook 14 OLED Touch', 'Performance Laptops', 37.84, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (248, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Intel/AMD Laptops', 74.17, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (249, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Performance Laptops', 33.17, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (250, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 6.73, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (251, 'Macbook Pro M2', 'ARM Laptops', 74.67, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (252, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 79.21, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (253, 'Macbook Pro M1', 'Intel/AMD Laptops', 84.7, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (254, 'Dell Precision 5690', 'Intel/AMD Laptops', 41.93, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (255, 'Macbook Pro M1', 'Performance Laptops', 37.11, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (256, 'Macbook Pro M2', 'Intel/AMD Laptops', 28.97, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (257, 'Dell Precision 5690', 'ARM Laptops', 89.52, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (258, 'Dell Precision 5690', 'Intel/AMD Laptops', 56.49, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (259, 'Lenovo Yoga 9i 14 Gen 9', 'Intel/AMD Laptops', 68.18, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (260, 'Lenovo Yoga 9i 14 Gen 9', 'Performance Laptops', 90.6, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (261, 'Lenovo ThinkPad X1 Carbon Gen 12', 'ARM Laptops', 38.41, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (262, 'Macbook Pro M1', 'ARM Laptops', 85.16, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (263, 'Macbook Air M3', 'Professional Laptops', 70.56, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (264, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 97.03, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (265, 'Macbook Pro M4', 'ARM Laptops', 16.64, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (266, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Intel/AMD Laptops', 80.19, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (267, 'Macbook Pro M4', 'Professional Laptops', 47.1, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (268, 'Asus ProArt P16 (H7606)', 'Intel/AMD Laptops', 10.84, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (269, 'Microsoft Surface Laptop 7', 'Business Laptops', 58.77, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (270, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 43.8, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (271, 'ASUS Zenbook 14 OLED Touch', 'ARM Laptops', 56.12, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (272, 'Asus ProArt P16 (H7606)', 'ARM Laptops', 66.39, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (273, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 75.52, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (274, 'Microsoft Surface Laptop 7', 'Professional Laptops', 40.91, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (275, 'Macbook Pro Intel i9', 'Professional Laptops', 62.58, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (276, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 22.8, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (277, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 24.28, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (278, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 68.11, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (279, 'Microsoft Surface Laptop 7', 'Performance Laptops', 30.88, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (280, 'Macbook Pro Intel i9', 'Professional Laptops', 94.8, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (281, 'Asus ProArt P16 (H7606)', 'Intel/AMD Laptops', 25.13, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (282, 'Dell Precision 5690', 'Professional Laptops', 34.17, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (283, 'Macbook Pro M4', 'Business Laptops', 49.72, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (284, 'Macbook Pro M1', 'Performance Laptops', 11.95, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (285, 'Lenovo Yoga 9i 14 Gen 9', 'Professional Laptops', 55.62, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (286, 'Asus ProArt P16 (H7606)', 'Performance Laptops', 78.11, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (287, 'Dell Precision 5690', 'Business Laptops', 21.08, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (288, 'Macbook Pro M4', 'Performance Laptops', 50.5, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (289, 'ASUS Zenbook 14 OLED Touch', 'Intel/AMD Laptops', 24.61, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (290, 'Lenovo ThinkPad X1 Carbon Gen 12', 'Business Laptops', 38.44, 'Pre-order');
insert into products (product_id, product_name, category, price, stock_level) values (291, 'Macbook Pro Intel i9', 'Performance Laptops', 22.74, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (292, 'Macbook Pro M2', 'Intel/AMD Laptops', 21.63, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (293, 'Macbook Pro M4', 'Performance Laptops', 88.56, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (294, 'Dell Precision 5690', 'Business Laptops', 10.12, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (295, 'Lenovo Yoga 9i 14 Gen 9', 'Business Laptops', 38.16, 'Stock exhausted');
insert into products (product_id, product_name, category, price, stock_level) values (296, 'Microsoft Surface Laptop 7', 'Intel/AMD Laptops', 53.9, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (297, 'Asus ProArt P16 (H7606)', 'Performance Laptops', 24.96, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (298, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 52.62, 'Not Available');
insert into products (product_id, product_name, category, price, stock_level) values (299, 'Macbook Air M3', 'Intel/AMD Laptops', 40.1, 'Available');
insert into products (product_id, product_name, category, price, stock_level) values (300, 'Lenovo Yoga 9i 14 Gen 9', 'ARM Laptops', 51.05, 'Pre-order');
